### ISSUE TITLE
GitHub support for syntax

### ISSUE THREAD

**Issue by Stilic** [Magnumsrt/Blue-Public#2]
i will find how to add it lol

**Comment by Stilic** [comment]
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by Magnumsrt** [comment]
They said: We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in at least 200 unique :user/:repo repositories before supporting them in Linguist.
